version: '3.8'
services:
  podcast:
    build: .
    container_name: pody
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
    restart: unless-stopped

